### ISSUE TITLE
Removing the usage of __progname for compat with uclibc

### ISSUE THREAD

**Issue by schultetwin1** [troglobit/libite#16]
I would like to remove the usage of `__progname` in pidfile.c in order to be able to use libite (and thus finit) on uclibc based devices. Work to remove __progname was already done in [finit](https://github.com/troglobit/finit/commit/f24a03a32c270a79653d74fffc107c21917b8bc4) but since it's still used in libite, uclibc is unable to link finit.

If you would be supportive of that work, I have three suggestions for how we could do it:

1) Mimic the `finit` approach, where the user must set a global variable which holds progname (probably taken from `argv[0]`)

2) Use `readlink`  and `basename` on `/proc/self/exe` to extract the program name.

3) Change the `pidfile` API to require the parameter `basename` not be `NULL`

My vote would be option 2, and both option 1 and 3 could be seen as a breaking change.

**Comment by troglobit** [comment]
Interesting.  I remember this being an issue way back, but these days uClibc has `__progname` support: https://git.busybox.net/uClibc/tree/extra/Configs/Config.in#n829

Anyway, if it didn't, I wouldn't like changing the behavior of `pidfile()` just for uClibc.  So options 1 and 3 are out of question.  Not too fond of option n:o 2 either, since I assume you mean changing the behavior for all users, not just `#ifdef __UCLIBC__`?

Probing the the existence of `__progname` in configure.ac at build-time though would be better in my opinion.  And then provide wrapper functions for have/haven't, or `#ifdefs` for the two cases.

**Comment by schultetwin1** [comment]
> I remember this being an issue way back, but these days uClibc has __progname support

Ah crap, you are correct. My apologies for missing that. It appears the project I inherited set `UCLIBC_HAS___PROGNAME` to `n`.

SInce uClibc, by default, has `__progname` I will work around this on my end and not modify libite. Thanks!
